#!/bin/bash

# ================== FILE MANAGEMENT ================
y0_filename=y0_test.txt				# where the initial values will be stored
output_directory=test				# folder where the run data will be stored
output_filename=test_run.pkl			# file where the run data will be stored, must be .pkl
make_plots=1					# 0=False, 1=True, if true makes figures of initialization properties saved in folder "initialization_figures"


# ================== RUN PROPERTIES =================
run_length=3600					# how long to run the simulation, s
dt=1.0						# time step for writing files


# ============== PARTICLE PROPERTIES ================
particles=1000					# number of simulated particles
Ntot=15000					# total number concentration (#/cm^3)
mode_mean_diameters=[250,650]			# geometric mean diameter of lognormal modes (nm), must be in format [mode1,mode2,....,modeX] (no spaces)
mode_standard_deviations=[1.1,1.5]		# geometric standard deviation of lognormal modes, must be in format [mode1,mode2,....,modeX] (no spaces)
mode_fractions=[0.3,0.7]			# fraction of particles placed in each lognormal mode, must be in format [mode1,mode2,....,modeX] (no spaces, must add up to 1)
avg_POM_fraction=0.9				# average POA mass fraction in particles, gaussian distribution, goes from (0, 1]
POM_fraction_std=0.05				# standard deviation of POA mass fraction in particles, gaussian distribution, goes from (0, 1]
min_sulfate_fraction=0.01			# minumum mass fraction of sulfate in particles, goes from (0, 1]


# ============= GAS/PARCEL PROPERTIES ================
SO2_gas=0.1					# initial SO2 gas concentration, ppb
OH_gas=4.5E-5					# initial OH gas concentration, ppb
O3_gas=2.6E-2					# initial O3 gas concentration, ppb
O3_photolysis_rate=3.553e-5			# rate at which O3 + hv --> O1D + O2, 1/s
H2SO4_gas=1E-25					# initial H2SO4 gas concentration, ppb (must be > 0)
temperature=315					# temperature (K)
ambient_SS=-0.15				# initial ambient supersaturation
ambient_P=101325				# initial ambient pressure, Pa
updraft_velocity=0.0				# updraft velocity of air parcel, m/s
condens_coeff=1.0 				# condensation coefficient for water vapor
thermal_accom=0.96 				# thermal accomodation coefficient





# ================================== set initial values

python3 initialize.py ${temperature} ${y0_filename} ${Ntot} ${mode_mean_diameters} ${mode_standard_deviations} ${mode_fractions} ${particles} ${make_plots} ${avg_POM_fraction} ${POM_fraction_std} ${min_sulfate_fraction} ${ambient_SS} ${ambient_P} ${SO2_gas} ${OH_gas} ${H2SO4_gas} ${O3_gas}

# ================================== run the simulation

python3 MAIN.py ${y0_filename} ${updraft_velocity} ${condens_coeff} ${thermal_accom} ${run_length} ${dt} ${temperature} ${output_directory} ${output_filename} ${O3_photolysis_rate}



















